"""add notification_snoozes table

Revision ID: 1e2f3a4b5c6d
Revises: 0d1e2f3a4b5c
Create Date: 2026-04-08 19:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1e2f3a4b5c6d'
down_revision: Union[str, None] = '0d1e2f3a4b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_snoozes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('notification_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_snoozes_id'), 'notification_snoozes', ['id'], unique=False)
    op.create_index(op.f('ix_notification_snoozes_notification_id'), 'notification_snoozes', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_snoozes_user_id'), 'notification_snoozes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_snoozes_user_id'), table_name='notification_snoozes')
    op.drop_index(op.f('ix_notification_snoozes_notification_id'), table_name='notification_snoozes')
    op.drop_index(op.f('ix_notification_snoozes_id'), table_name='notification_snoozes')
    op.drop_table('notification_snoozes')
    # ### end Alembic commands ###
